fix (#119): Revise get_budget query
hammem/monarchmoney pull request #120
Opened 2024-12-25 11:38 UTC by Sean280ZX

Remove option to use legacy v1 goals.   Update gql query

2024-12-27 08:39 UTC, Sean280ZX commented
@hammem This pull request is ready to review.

2025-01-07 17:38 UTC, bradRenshaw approved these changes

2025-01-19 15:52 UTC, hammem requested changes
Thanks, @Sean280ZX , for updating this function!  Please add a test for it similar to what exists for some of the calls already.  I've been trying to add coverage as things change/update (see #83 ) to reduce errors for folks in the future.

2025-02-03 00:16 UTC, hammem approved these changes
Thanks, @Sean280ZX !

2025-02-03 00:16 UTC, merged