Change default limits to 100 to match docs
hammem/monarchmoney pull request #44
Opened 2023-11-20 18:12 UTC by guillochon

The docs say the default return is 100, whereas the code is 1000. I think having a smaller number as a default makes more sense, as the defaults will primarily be used by new users figuring out the library.

2023-11-22 21:09 UTC, hammem requested changes
Thanks, @guillochon !  Can you define it as a 'constant', so it's easier to maintain or if folks want to change it when using the library?

2023-11-22 23:17 UTC, guillochon commented
Done.

2023-11-23 00:39 UTC, hammem approved these changes
One small thing and then we can merge!

2023-11-23 00:39 UTC, hammem commented on monarchmoney/monarchmoney.py
> +DEFAULT_RECORD_LIMIT = 100
nit: please alphabetize

2023-11-23 04:29 UTC, merged