added support for institutions
hammem/monarchmoney pull request #68
Opened 2024-01-11 19:12 UTC by pazwicker

2024-01-11 23:30 UTC, hammem requested changes
Thanks, @pazwicker !  Just a small thing for spelling on 'institution' in a couple of places.

2024-01-11 23:30 UTC, hammem commented on main.py
> +    with open("insitutions.json", "w") as outfile:
Nit: spelling on 'institution'

2024-01-11 23:30 UTC, hammem commented on monarchmoney/monarchmoney.py
> +        Gets insitution data from the account.
Nit: spelling

2024-01-12 02:01 UTC, pazwicker commented on main.py
> +    with open("insitutions.json", "w") as outfile:
Thanks for the catch!

2024-01-12 02:02 UTC, pazwicker commented on monarchmoney/monarchmoney.py
> +        Gets insitution data from the account.
And again!

2024-01-12 02:21 UTC, hammem approved these changes
Awesome!  Thanks again for the contributions. The library is growing in functionality so much faster with all the help!

2024-01-12 02:21 UTC, merged